AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ColorSplashPhotoProcessor

  Sample SAM Template for ColorSplashPhotoProcessor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ColorSplashPhotoProcessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8

Outputs:
  ColorSplashPhotoProcessorFunction:
    Description: "ColorSplashPhotoProcessor Lambda Function ARN"
    Value: !GetAtt ColorSplashPhotoProcessorFunction.Arn
  ColorSplashPhotoProcessorFunctionIamRole:
    Description: "Implicit IAM Role created for ColorSplashPhotoProcessor function"
    Value: !GetAtt ColorSplashPhotoProcessorFunctionRole.Arn
