AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ColorSplashPhotoProcessor

  Sample SAM Template for ColorSplashPhotoProcessor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ColorSplashPhotoProcessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 512
      Timeout: 100
      Description: A Lambda function that returns a status code.
      FunctionName: ColorSplashPhotoProcessor
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Layers:
        - arn:aws:lambda:us-west-1:015914662809:layer:cv2-python38:4
        - arn:aws:lambda:us-west-1:325793726646:layer:AWSLambda-Python38-SciPy1x:29